export const USERNAME_OR_PASSWORD_NOT_MATCH: string = 'USERNAME_OR_PASSWORD_NOT_MATCH'
export const CAPTCHA_NOT_MATCH: string = 'CAPTCHA_NOT_MATCH'
export const USERNAME_ALREADY_EXISTS: string = 'USERNAME_ALREADY_EXISTS'
