// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElC: typeof import('element-plus/es')['ElC']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToolCard: typeof import('./components/ToolCard/index.vue')['default']
  }
}
